name: CD Pipeline

on:
  push:
    paths:
      - 'Terraform/**'
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read
  security-events: write


env:
  IMAGE_NAME: "jenkins-image"
  IMAGE_RESOURCE_GROUP: "vmImage"
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_admin_username: "azureuser"
  TF_VAR_admin_public_key_path: "id_rsa.pub"


jobs:
  Terrafrom-scan-Checkov:
    if: github.event.inputs.action == 'apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: Terraform
          soft_fail: true
          framework: terraform
          output_format: sarif
          output_file_path: results.sarif

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif


  Terraform-apply:
    if: github.event.inputs.action == 'apply'
    needs: Terrafrom-scan-Checkov
    runs-on: ubuntu-latest
    environment: AZURE_SP
    defaults:
      run:
        working-directory: Terraform
    steps:
      - uses: actions/checkout@v3
      - name: Save SSH public key to file
        run: |
          echo "${{ secrets.VM_SSH_PUBLIC_KEY }}" > id_rsa.pub
          chmod 600 id_rsa.pub

      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Refresh
        run: terraform refresh

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply or Destroy
        run: terraform apply -auto-approve


  Terraform-Destroy:
    if: github.event.inputs.action == 'destroy'
    runs-on: ubuntu-latest
    environment: AZURE_SP
    defaults:
      run:
        working-directory: Terraform
    steps:
      - uses: actions/checkout@v3
      
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Refresh
        run: terraform refresh

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply or Destroy
        run: terraform destroy -auto-approve



    
        
                
          
