name: CD Pipeline

on:
  push:
    paths:
      - 'Terraform/**'
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read
  security-events: write



jobs:
  Terraform-scan-Checkov:
    if: github.event.inputs.action == 'apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: Terraform
          soft_fail: true
          framework: terraform
          output_format: sarif
          output_file_path: results.sarif

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif


  Terraform-apply:
    if: github.event.inputs.action == 'apply'
    needs: Terraform-scan-Checkov
    runs-on: ubuntu-latest
    env:
      TF_VAR_admin_username: "azureuser"
      TF_VAR_admin_public_key_path: "id_rsa.pub"
    defaults:
      run:
        working-directory: Terraform
    steps:
      - uses: actions/checkout@v3
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Save SSH public key to file
        run: |
          echo "${{ secrets.VM_SSH_PUBLIC_KEY }}" > id_rsa.pub
          chmod 600 id_rsa.pub

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply or Destroy
        run: terraform apply -auto-approve


  Terraform-Destroy:
    if: github.event.inputs.action == 'destroy'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform
    steps:
      - uses: actions/checkout@v3
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply or Destroy
        run: terraform destroy -auto-approve



    
        
                
          
