name: Continuous Integration - Packer Build

on:
  push:
    paths:
      - 'Packer/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  IMAGE_NAME: "jenkins-image"
  IMAGE_RESOURCE_GROUP: "vmImage"
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  PACKER_LOG: "1"

jobs:
  trivyscan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.31.0
        with:
          scan-type: fs
          scan-ref: ./Packer
          scanners: secret
          format: table
          severity: HIGH,CRITICAL


  packer-build:
    needs: trivyscan
    runs-on: ubuntu-latest
    environment: AZURE_SP
    defaults:
      run:
        working-directory: Packer
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-packer@v2
      - name: Init, validate, build packer image          
        run: |
          packer init azjenkins.pkr.hcl
          packer validate -var "client_id=$ARM_CLIENT_ID" -var "client_secret=$ARM_CLIENT_SECRET" -var "tenant_id=$ARM_TENANT_ID" -var "subscription_id=$ARM_SUBSCRIPTION_ID" azjenkins.pkr.hcl
          packer build -force -var "client_id=$ARM_CLIENT_ID" -var "client_secret=$ARM_CLIENT_SECRET" -var "tenant_id=$ARM_TENANT_ID" -var "subscription_id=$ARM_SUBSCRIPTION_ID" azjenkins.pkr.hcl


              
  
