name: Continuous Integration - Packer Build

on:
  push:
    paths:
      - 'Packer/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  IMAGE_NAME: "jenkins-image"
  IMAGE_RESOURCE_GROUP: "vmImage"
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  PACKER_LOG: "1"

jobs:
  trivyscan:
    runs-on: ubuntu-latest
    steps:
      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.31.0
        with:
          scan-type: fs
          scan-ref: ./Packer
          format: table
          severity: HIGH,CRITICAL
              
  
